database:
  host: "no"
  port: 3306
  database: "no"
  username: "no"
  password: "no"

MESSAGES:
  NO_PERMISSION: '&cYou dont have permission to perform this command.'

max_level: 10

level_requirements:
  2: 2500
  3: 7500
  4: 15000
  5: 25000
  6: 50000
  7: 150000
  8: 250000
  9: 500000
  10: 1000000


level_rewards:
  2:
    commands:
      - 'lp user %player% parent add sl-2'
    message:
      - ''
      - '&f[&bSurvival&f] &bYou reached Survival Level &b2!'
      - ''
  3:
    commands:
      - 'lp user %player% parent add sl-3'
    message:
      - ''
      - '&f[&bSurvival&f] &bYou reached Survival Level &b3!'
      - ''
  4:
    commands:
      - 'lp user %player% parent add sl-4'
    message:
      - ''
      - '&f[&bSurvival&f] &bYou reached Survival Level &b4!'
      - ''
  5:
    commands:
      - 'lp user %player% parent add sl-5'
    message:
      - ''
      - '&f[&bSurvival&f] &bYou reached Survival Level &b5!'
      - ''
  6:
    commands:
      - 'lp user %player% parent add sl-6'
    message:
      - ''
      - '&f[&bSurvival&f] &bYou reached Survival Level &b6!'
      - ''
  7:
    commands:
      - 'lp user %player% parent add sl-7'
    message:
      - ''
      - '&f[&bSurvival&f] &bYou reached Survival Level &b7!'
      - ''
  8:
    commands:
      - 'lp user %player% parent add sl-8'
    message:
      - ''
      - '&f[&bSurvival&f] &bYou reached Survival Level &b8!'
      - ''
  9:
    commands:
      - 'lp user %player% parent add sl-9'
    message:
      - ''
      - '&f[&bSurvival&f] &bYou reached Survival Level &b9!'
      - ''
  10:
    commands:
      - 'lp user %player% parent add sl-10'
    message:
      - ''
      - '&f[&bSurvival&f] &bYou reached Survival Level &b10!'
      - ''

lore_outcomes:
  pass: '&aYou have completed this level.'
  fail: '&cEarn xp to unlock this level.'

level_items:
  #https://minecraft-heads.com/custom-heads/alphabet/19252-plush-2
  menu_texture: 'https://textures.minecraft.net/texture/6f9a2c9e35b7381efcc3851b664cd8de21ffc6f377070f8193cdaf18cd95876c'
  1:
    NAME: '&a&lLevel 1'
    TEXTURE: 'https://textures.minecraft.net/texture/e0a4c94dd65a7cadc4172cedf3990a8542772bb113cdf1a0f78ef652c6abe6cb'
    LORE:
      - '&7This level is unlocked by default, earn xp'
      - '&7through different ways to unlock new levels.'
  2:
    NAME: '&5&lLevel 2'
    TEXTURE: 'https://textures.minecraft.net/texture/a47c55064f1d07625af05cdbc0fc7c84173b10541024c8855ed7132ca7767246'
    LORE:
      - '&7You will automatically unlock this level and its perks'
      - '&7after you have earned the required amount of level experience.'
      - ''
      - '&7XP Required: &b%xp_required%'
      - ''
      - '&7Unlocks:'
      - '&55% Increase &7for gaining level experience'
      - '&5Auction House &7full access'
      - '&510 &7Legacy Coins'
      - ''
      - '%lore_outcome%'
  3:
    NAME: '&3&lLevel 3'
    TEXTURE: 'https://textures.minecraft.net/texture/d9cb94d8729197a18a76882c24918a8c04494d34727f4df060fb7a45a1ff8537'
    LORE:
      - '&7You will automatically unlock this level and its perks'
      - '&7after you have earned the required amount of level experience.'
      - ''
      - '&7XP Required: &b%xp_required%'
      - ''
      - '&7Unlocks:'
      - '&35% Increase &7for gaining level experience'
      - '&3Auction House &7full access'
      - '&310 &7Legacy Coins'
      - ''
      - '%lore_outcome%'
  4:
    NAME: '&e&lLevel 4'
    TEXTURE: 'https://textures.minecraft.net/texture/36ad7565fa68942d2ff5f04efda80d9e9f88d33401680f182e0f37af32b8c294'
    LORE:
      - '&7You will automatically unlock this level and its perks'
      - '&7after you have earned the required amount of level experience.'
      - ''
      - '&7XP Required: &b%xp_required%'
      - ''
      - '&7Unlocks:'
      - '&e5% Increase &7for gaining level experience'
      - '&eAuction House &7full access'
      - '&e10 &7Legacy Coins'
      - ''
      - '%lore_outcome%'
  5:
    NAME: '&9&lLevel 5'
    TEXTURE: 'https://textures.minecraft.net/texture/d0203b124acefd08c446a0492a5c9d800ee0cd8c260c3c12377731659251ad4e'
    LORE:
      - '&7You will automatically unlock this level and its perks'
      - '&7after you have earned the required amount of level experience.'
      - ''
      - '&7XP Required: &b%xp_required%'
      - ''
      - '&7Unlocks:'
      - '&95% Increase &7for gaining level experience'
      - '&9Auction House &7full access'
      - '&910 &7Legacy Coins'
      - ''
      - '%lore_outcome%'
  6:
    NAME: '&d&lLevel 6'
    TEXTURE: 'https://textures.minecraft.net/texture/e491017fd5267fc9a641cce0250d4683804e3b1399b2b5b58f130f5774de2821'
    LORE:
      - '&7You will automatically unlock this level and its perks'
      - '&7after you have earned the required amount of level experience.'
      - ''
      - '&7XP Required: &b%xp_required%'
      - ''
      - '&7Unlocks:'
      - '&d5% Increase &7for gaining level experience'
      - '&dAuction House &7full access'
      - '&d10 &7Legacy Coins'
      - ''
      - '%lore_outcome%'
  7:
    NAME: '&c&lLevel 7'
    TEXTURE: 'https://textures.minecraft.net/texture/8425acc42caf8b1e95ccb16d379af0b76f95ed29ef2a494073d0b07b15dc22fd'
    LORE:
      - '&7You will automatically unlock this level and its perks'
      - '&7after you have earned the required amount of level experience.'
      - ''
      - '&7XP Required: &b%xp_required%'
      - ''
      - '&7Unlocks:'
      - '&c5% Increase &7for gaining level experience'
      - '&cAuction House &7full access'
      - '&c10 &7Legacy Coins'
      - ''
      - '%lore_outcome%'
  8:
    NAME: '&5&lLevel 8'
    TEXTURE: 'https://textures.minecraft.net/texture/b4904d5dee3782d4d6c6febe72783d96148277efbe78c1514cc20088d8ff0d09'
    LORE:
      - '&7You will automatically unlock this level and its perks'
      - '&7after you have earned the required amount of level experience.'
      - ''
      - '&7XP Required: &b%xp_required%'
      - ''
      - '&7Unlocks:'
      - '&55% Increase &7for gaining level experience'
      - '&5Auction House &7full access'
      - '&510 &7Legacy Coins'
      - ''
      - '%lore_outcome%'
  9:
    NAME: '&b&lLevel 9'
    TEXTURE: 'https://textures.minecraft.net/texture/6adc65c3b896ab66df1ed7ba4250d16bb8352a6d285a54c00218ea72a4bb7149'
    LORE:
      - '&7You will automatically unlock this level and its perks'
      - '&7after you have earned the required amount of level experience.'
      - ''
      - '&7XP Required: &b%xp_required%'
      - ''
      - '&7Unlocks:'
      - '&b5% Increase &7for gaining level experience'
      - '&bAuction House &7full access'
      - '&b10 &7Legacy Coins'
      - ''
      - '%lore_outcome%'
  10:
    NAME: '&3&lLevel 10'
    TEXTURE: 'https://textures.minecraft.net/texture/abd267503356c851f739556847575b5e338814a73b3ae8abc65ae40cf16cc333'
    LORE:
      - '&7You will automatically unlock this level and its perks'
      - '&7after you have earned the required amount of level experience.'
      - ''
      - '&7XP Required: &b%xp_required%'
      - ''
      - '&7Unlocks:'
      - '&35% Increase &7for gaining level experience'
      - '&3Auction House &7full access'
      - '&310 &7Legacy Coins'
      - ''
      - '%lore_outcome%'