database:
  host: "no"
  port: 3306
  database: "no"
  username: "no"
  password: "no"

MESSAGES:
  NO_PERMISSION: '&cYou dont have permission to perform this command.'

max_level: 10

level_requirements:
  2: 2500
  3: 7500
  4: 15000
  5: 25000
  6: 50000
  7: 150000
  8: 250000
  9: 500000
  10: 1000000

level_rewards:
  2:
    commands:
      - 'msg %player% you reached level 2'
    message:
      - ''
      - '&bYou reached level 2'
      - ''