name: SurvivalLevels
version: '${project.version}'
main: net.guildcraft.survivallevels.SurvivalLevels
api-version: 1.20
author: Frxq15

commands:
  level:
    description: level command
    aliases: [levels, survivallevel, survivallevels, slevel]
  givelevelxp:
    description: givelevelxp command
    aliases: [addlevelxp]